[package]
name = "rust_graph_visualiser"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
macroquad = { version = "0.3.25" }

[dev-dependencies]
rand = { version = "0.8.5" }
