[package]
name = "rust_graph_visualiser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
macroquad = { version = "0.4.2" }
rand = { version = "0.8.5" }
