[package]
name = "rust_graph_visualiser"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
egui-macroquad = "0.15.0"
macroquad = "0.3.26"
rand = "0.8.5"
