attr_fn_like_width = 120
chain_width = 0
fn_args_layout = "Compressed"
fn_call_width = 120
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 120
tab_spaces = 2
use_field_init_shorthand = true
# use_small_heuristics = "Max"
fn_single_line = true
where_single_line = true
struct_lit_single_line = true
empty_item_single_line = true
disable_all_formatting = true
